INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'I like','minä pidän');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'easy','helppo');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'difficult','vaikea');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'I am learning (in progress)','opiskelen');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'I learned (before)','opin');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'hello','terve, hei, moi');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'nice','mukava');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'sorry, excuse me','anteeksi');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'thank you','kiitos');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'funny','hauska');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'good luck, congratulations','onnea');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'well','no');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'so','niin');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'a lot (of)','paljon');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'man','mies');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'woman','nainen');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'child','lapsi');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'beautiful','kaunis');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'handsome','komea');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'really','todella');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'always','aina');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'instrument','soitin');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'boy','poika');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'girl','tyttö');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'person, human being','ihminen');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'friend','ystävä');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'shy','ujo');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'Mr. and Mrs.','Herra ja Rouva');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'incorrect/wrong','väärin');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'green','vihreä');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'black','musta');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'white','valkoinen');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'blue','sininen');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'small','pieni');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'naughty','tuhma');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'stupid','tyhmä');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'cute, adorable','söpö');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'cat','kissa');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'dog','koira');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'snake','käärme');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'cold','kylmä');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'hot','kuuma');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'city','kaupunki');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'song','laulu');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'viking','viikinki');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'name','nimi');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'cell phone','kännykkä');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'car','auto');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'strange','outo');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'big','iso');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'pet','lemmikki');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'mother','äiti');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'father','isä');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'grandma','mummo');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'grandpa','vaari');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'baby','vauva');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'couple','pari');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'toy','lelu');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'teddy','nalle');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'family','perhe');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'sad','surullinen');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'young','nuori');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'to laugh','nauraa');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'to sing','laulaa');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'to grow','kasvaa');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'to stand','seisoa');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'to sit','istua');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'to dance','tanssia');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'to cry ','itkeä');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'to drive','ajamaan');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'now','nyt');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'often','usein');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'seldom','harvoin');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'fast, quickly','nopeasti');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'married','naimisissa');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'single (not married)','naimaton');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'single','sinkku');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'divorced','eronnut');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'widow','leski');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'husband (special one)','aviomies');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'wife','vaimo');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'spouse','puoliso');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'husband and wife (in an open marriage)','avomies, avovaimo');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'student','opiskelija');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'teacher','opettaja');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'chef','kokki');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'doctor','lääkäri');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'retired','eläkeläinen');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'day (days)','päivä (päivää)');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'week (weeks)','viikko (viikkoa)');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'month (months)','kuukausi (kuukautta)');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'year (years)','vuosi (vuotta)');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'what about','entä');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'before','ennen');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'understand','ymmärrä');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'unemployed','työtön');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'at work','työssä');
INSERT INTO `words` (`times_used`, `translation`, `word`) VALUES (0,'pen','kynä');